rm(list=ls())
mydata = read.table("household_power_consumption.txt",header = TRUE, sep = ";",na.strings=c("?"))
mydata$Date <- as.Date(mydata$Date,format="%d/%m/%Y")
#mydata$Time <- strptime(mydata$Time,format="%H:%M:%S")
submydata = subset(mydata, as.Date(Date) >= '2007-02-01' & as.Date(Date) <= '2007-02-02')
submydata$datetime <- as.POSIXct(paste(submydata$Date, submydata$Time), format="%Y-%m-%d %H:%M:%S")


png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(submydata$datetime,submydata$Global_active_power,type='l',lwd=1, xlab="", ylab = 'Global Active Power')
plot(submydata$datetime,submydata$Voltage,type='l',lwd=1,xlab="datetime",ylab="Voltage")
plot(submydata$datetime,submydata$Sub_metering_1,type='l',lwd=1,col='black', xlab="", ylab="Engergy sub metering")
lines(submydata$datetime,submydata$Sub_metering_2,type='l',lwd=1,col='red')
lines(submydata$datetime,submydata$Sub_metering_3,type='l',lwd=1,col='blue')
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
plot(submydata$datetime,submydata$Global_reactive_power,type='l',lwd=1,xlab="datetime",ylab="Global_reactive_power")
dev.off()